### PR TITLE
Updated rendering of the files in web-ui

### PR DESCRIPTION
**Pull request by dharmez**
I have modified a few functions to render PDF and other files in an iframe.

### CODE REVIEW

**Review by mescanne — COMMENTED** [review]
There are some style/layout changes and there is the threshold for the max file size (1.5MB) for the embedded PDF viewer.

There's also a shift from using the mime_type from GCS -- the content_type of the blob -- to inferring it from the extension. Is there a benefit / need for this?

The rendering code for the GCS object is also in the api.py file, while the original thinking was for common rendering code (such as this) to be in components.py with the actual interaction with the GCP API is in api.py (where @st.cache_resource is etc).

**Comment by mescanne** [comment]
Dharmesh -- please check out the sugested changes. I've added the Download button back and made it configurable whether to link to the console or a direct object link (depending on auditing permissions etc).

There are other ways this can be improved, but I'm conscious of limiting the focus and getting things merged.

In terms of mimetype -- I removed this logic, and I was thinking we could add logic in there that if the GCS object as octet-stream then we can infer the type from the extension.

**Review by dharmez — COMMENTED** [review]
I made a few changes to documentation and Web-UI

**Review by dharmez — COMMENTED** [review]
Reviewed the changes and updated the link to Open the document.

**Review by mescanne — APPROVED** [review]

**Pull request merged**
